import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../src/components/header'
import VerticalCard from '../src/components/verticalCard'

export default function Home() {

  const n = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  return (
    <div className={styles.container}>
      <Head>
        <title>SKLC - Videos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {n.map(() => (
        <VerticalCard />
      ))}
      <button>Load more</button>
    </div>
  )
}
